---
version: "3"
services:
  nginx:
    image: nginx:1.25-alpine
    ports:
      - 80:80
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - portfolio
  php:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    ports:
      - 9000:9000
    volumes:
      - ./:/var/ww/html
    networks:
      - portfolio

networks:
  portfolio:
    driver: bridge
